/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Grid: typeof import('./src/components/Grid/index.vue')['default']
    GridItem: typeof import('./src/components/Grid/components/GridItem.vue')['default']
    ProcessForm: typeof import('./src/components/ProcessForm/index.vue')['default']
    ProcessFormItem: typeof import('./src/components/ProcessForm/components/ProcessFormItem.vue')['default']
  }
}
